export const ENV = {
  MODE: process.env.NEXT_PUBLIC_MODE,
  SESSION_COOKIE_NAME: String(process.env.SESSION_COOKIE_NAME),
  URI: {
    BASE_URL: process.env.BASE_URL,
    BASE_URL_SERVICE_PRODUCT: process.env.BASE_URL_SERVICE_PRODUCT,
    WS_CHAT_URL: process.env.WS_CHAT_URL,
    CRYPTOGRAPHY_PIN_ENCRYPTION_KEY:
      process.env.CRYPTOGRAPHY_PIN_ENCRYPTION_KEY,
  },
  CURRENCY: "IDR",
  DEFAULT_LANG: "ID",
  CRYPTOGRAPHY_PIN_ENCRYPTION_KEY: process.env.CRYPTOGRAPHY_PIN_ENCRYPTION_KEY,
  CRYPTOGRAPHY_PIN_CONFIRMATION_ENCRYPTION_KEY:
    process.env.CRYPTOGRAPHY_PIN_CONFIRMATION_ENCRYPTION_KEY,
  SESSION_SECRET_KEY: process.env.SESSION_SECRET_KEY,
  FILE_SIZE_LIMIT: Number(process.env.FILE_SIZE_LIMIT),
};
